@host = localhost:8080


POST http://{{host}}/api/secured/product HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1heC5tdXN0ZXJtYW5uIiwiZXhwIjoxNjY1OTI1NDg5fQ.VoJS5mCRJ2mhKLErGtnla_esZzl7_rNgCdpW6jW8FmY
    
{
    "sellerID": 3,
    "amountAvailable": 150,
    "productName": "Coca-Cola",
    "cost": 5
}

###





POST http://{{host}}/api/secured/product/buy HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRvbi5kcmFwZXIiLCJleHAiOjE2NjU5NjA3MDR9.LjM4U0FTlg_p8BJuNC-dSvYbt1SJFAbvP79CAzZMBvA
    
{
    "productID": 3,
    "amount": 4
}