@host = localhost:8080


POST http://{{host}}/api/secured/product HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1heC5tdXN0ZXJtYW5uIiwiZXhwIjoxNjY2MDM0MzEyfQ.EPcn4g7ILx-KWAZFpUMkKk5jw6GewAqGjG1ZzkWQrfU
    
{
    "sellerID": 3,
    "amountAvailable": 150,
    "productName": "Sprite",
    "cost": 5
}

###





POST http://{{host}}/api/secured/product/buy HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRvbi5kcmFwZXIiLCJleHAiOjE2NjU5NjA3MDR9.LjM4U0FTlg_p8BJuNC-dSvYbt1SJFAbvP79CAzZMBvA
    
{
    "productID": 3,
    "amount": 4
}

###


GET http://{{host}}/api/products/ HTTP/1.1
content-type: application/json

{
}

###

GET http://{{host}}/api/secured/products/ HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1heC5tdXN0ZXJtYW5uIiwiZXhwIjoxNjY2MTM1NDIyfQ.A1eQDuWCyj6LPVDgtrlr3ziEXZAGOTKkhQXUmMUitW0

{
}

###
GET http://{{host}}/api/secured/products/ HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlbGxlciIsImV4cCI6MTY2NjE0MjQ4Mn0.zTZCMFZo-QP8XLpq_j2D1lqHdHeVBQTGC0OPwE72qa0

{
}


###

DELETE http://{{host}}/api/secured/product/delete HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlbGxlciIsImV4cCI6MTY2NjE0MjQ4Mn0.zTZCMFZo-QP8XLpq_j2D1lqHdHeVBQTGC0OPwE72qa0

{
    "productID": 10
}