@host = localhost:8080

// Generate JWT
POST http://{{host}}/api/token HTTP/1.1
content-type: application/json
    
{
    "username": "max.mustermann",
    "password": "123465789"
}

###



POST http://{{host}}/api/token HTTP/1.1
content-type: application/json
    
{
    "username": "don.draper",
    "password": "123465789"
}

###



POST http://{{host}}/api/token HTTP/1.1
content-type: application/json
    
{
    "username": "buyer",
    "password": "12345678"
}

###

