@host = localhost:8080

// Register User
POST http://{{host}}/api/user/register HTTP/1.1
content-type: application/json
    
{

    "username": "max.mustermann",
    "password": "123465789",
    "deposit": 0,
    "role": "seller"
}

###

// Register User
POST http://{{host}}/api/user/register HTTP/1.1
content-type: application/json
    
{

    "username": "don.draper",
    "password": "123465789",
    "deposit": 0,
    "role": "buyer"
}

###

// LoginUser
POST http://{{host}}/api/user/login HTTP/1.1
content-type: application/json
    
{

    "username": "max.mustermann",
    "password": "123465789"
}
###

POST http://{{host}}/api/user/register HTTP/1.1
content-type: application/json
    
{
    "username": "matt.lovey",
    "password": "12345678",
    "role": "buyer"
}

###



DELETE http://{{host}}/api/user/register HTTP/1.1
content-type: application/json
    
{
    "username": "max.mustermann",
    "password": "123465789"
}

###



POST http://{{host}}/api/secured/deposit HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvbS5jcnVpc2UiLCJleHAiOjE2NjYxMjQzNjZ9.HxOH9HehyAC7oEPUI7Iwl_luVCZVsqypofJb_6gikwo
    
{
    "depositAmount": 100
}

###


POST http://{{host}}/api/secured/user/reset HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvbS5jcnVpc2UiLCJleHAiOjE2NjYxMjQzNjZ9.HxOH9HehyAC7oEPUI7Iwl_luVCZVsqypofJb_6gikwo
    
{
}

###


GET http://{{host}}/api/secured/user/ HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvbS5jcnVpc2UiLCJleHAiOjE2NjYxMjQzNjZ9.HxOH9HehyAC7oEPUI7Iwl_luVCZVsqypofJb_6gikwo

{
}

###


